### ISSUE TITLE
(copod) PyOD version for COPOD should be at least 1.0.9

### ISSUE THREAD

**Issue by Kotrix** [TimeEval/TimeEval-algorithms#43]
Hi,
there were two important fixes to COPOD in PyOD since version 0.9.2:
- https://github.com/yzhao062/pyod/commit/cbc8c9408c1d37c690fd2daf7fc628e986e0e077
- https://github.com/yzhao062/pyod/commit/6513cc0b6aae7d264f324196d0d831bbd32c2539 (which is not so minor as the title suggest because it decreases processing times and memory usage by half)

I suggest bumping the version to the latest 1.1.2, it works for me without any modifications
https://github.com/TimeEval/TimeEval-algorithms/blob/62cef737f04b13e2019427b2f589b644b9f3c5d9/copod/requirements.txt#L5

Regards,
Krzysztof

**Comment by CodeLionX** [comment]
Good catch!

Do you think that we should update PyOD to `latest` (or at least 1.0.0) for all our algorithms?

**Comment by Kotrix** [comment]
I've updated the version to the latest in most of those algorithms in my fork
